#!/usr/bin/env python3
"""
esttab2html.py — Convert esttab LaTeX output to HTML + docx via pandoc.

Usage:
    python esttab2html.py output/tables/main_table.tex
    python esttab2html.py output/tables/main_table.tex --title "Table 2: 基准回归"

Requires:
    pandoc (brew install pandoc)

Output:
    output/tables/main_table.html  — HTML (Obsidian 预览用)
    output/tables/main_table.docx — Word (CSSCI 投稿用)
"""

import argparse
import os
import subprocess
import sys
import tempfile
import re


def check_pandoc():
    """Verify pandoc is installed."""
    try:
        subprocess.run(["pandoc", "--version"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("错误: pandoc 未安装。macOS: brew install pandoc", file=sys.stderr)
        sys.exit(1)


def convert_to_html(tex_path, output_path):
    """Convert LaTeX to HTML."""
    result = subprocess.run(
        ["pandoc", tex_path, "-f", "latex", "-t", "html",
         "--quiet",
         "-o", output_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"HTML 转换失败: {result.stderr}", file=sys.stderr)
        return False
    return True


def convert_to_docx(tex_path, output_path):
    """Convert LaTeX to docx."""
    result = subprocess.run(
        ["pandoc", tex_path, "-f", "latex", "-t", "docx",
         "--quiet",
         "-o", output_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"docx 转换失败: {result.stderr}", file=sys.stderr)
        return False
    return True


def add_three_line_style(html_path, title=None):
    """
    Post-process HTML: ensure the table has proper three-line markup
    for Obsidian CSS rendering.
    """
    with open(html_path, encoding="utf-8") as f:
        html = f.read()

    # Ensure table has thead/tbody structure for three-line CSS
    # Pandoc already produces this, but we make it explicit
    if "<thead>" not in html or "<tbody>" not in html:
        print("警告: HTML 表格缺少 thead/tbody 结构，三线表样式可能无效", file=sys.stderr)

    # Add table note if title provided
    if title:
        note = f'<p class="table-title"><strong>{title}</strong></p>\n'
        html = note + html

    # Add Obsidian-compatible wrapper
    html = (
        f'<!-- Generated by esttab2html.py -->\n'
        f'{html}'
    )

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Convert esttab LaTeX table to HTML + docx"
    )
    parser.add_argument("input", help="Path to esttab .tex file")
    parser.add_argument("--title", "-t", help="Table title")
    parser.add_argument("--output-dir", "-d", help="Output directory (default: same as input)")

    args = parser.parse_args()

    check_pandoc()

    tex_path = args.input
    if not os.path.exists(tex_path):
        print(f"错误: 找不到文件 {tex_path}", file=sys.stderr)
        sys.exit(1)

    base = os.path.splitext(tex_path)[0]
    html_path = f"{base}.html"
    docx_path = f"{base}.docx"

    if args.output_dir:
        os.makedirs(args.output_dir, exist_ok=True)
        basename = os.path.splitext(os.path.basename(tex_path))[0]
        html_path = f"{args.output_dir}/{basename}.html"
        docx_path = f"{args.output_dir}/{basename}.docx"

    # 保留原来的 html 写入和检查
    ok = convert_to_html(tex_path, html_path)
    if not ok:
        sys.exit(1)
    print(f"✅ {html_path}")

    ok = convert_to_docx(tex_path, docx_path)
    if not ok:
        sys.exit(1)
    print(f"✅ {docx_path}")

    add_three_line_style(html_path, args.title)

    print(f"\n✅ 转换完成: {html_path} + {docx_path}")


if __name__ == "__main__":
    main()
